
uint32 ARM           = 0
uint32 ANGLE         = 1
uint32 HORIZON       = 2
uint32 NAVALTHOLD    = 3
uint32 HEADINGHOLD   = 4
uint32 HEADFREE      = 5
uint32 HEADADJ       = 6
uint32 CAMSTAB       = 7
uint32 NAVRTH        = 8
uint32 NAVPOSHOLD    = 9
uint32 MANUAL        = 10
uint32 BEEPERON      = 11
uint32 LEDLOW        = 12
uint32 LIGHTS        = 13
uint32 NAVLAUNCH     = 14
uint32 OSD           = 15
uint32 TELEMETRY     = 16
uint32 BLACK      = 17
uint32 FAILSAFE      = 18
uint32 NAVWP         = 19
uint32 AIRMODE       = 20
uint32 HOMERESET     = 21
uint32 GCSNAV        = 22
uint32 KILLSWITCH    = 23
uint32 SURFACE       = 24
uint32 FLAPERON      = 25
uint32 TURNASSIST    = 26
uint32 AUTOTRIM      = 27
uint32 AUTOTUNE      = 28
uint32 CAMERA1       = 29
uint32 CAMERA2       = 30
uint32 CAMERA3       = 31
uint32 OSDALT1       = 32
uint32 OSDALT2       = 33
uint32 OSDALT3       = 34
uint32 NAVCRUISE     = 35
uint32 BRAKING       = 36
uint32 USER1         = 37
uint32 USER2         = 38
uint32 FPVANGLEMIX   = 39
uint32 LOITERDIRCHN  = 40
uint32 MSPRCOVERRIDE = 41




Header header
uint32[] set
uint32[] add
uint32[] remove



